-------------------------------------------------------------------------------

create schema if not exists ${schema};

set local search_path to ${schema}, public;

-------------------------------------------------------------------------------

create or replace function ${schema}.now_utc() returns timestamp with time zone as $$
    select now() at time zone 'utc';
$$ language sql stable;

comment on function ${schema}.now_utc() is 'Returns the current UTC timestamp for defaulting created/updated columns.';

-------------------------------------------------------------------------------

create table if not exists ${schema}.generator (
    last_reserved bigint not null
);

insert into ${schema}.generator (last_reserved) values (1);

comment on table ${schema}.generator is 'Tracks the last reserved ID for manual ID generation';
comment on column ${schema}.generator.last_reserved is 'The last reserved ID for generating unique IDs';

-------------------------------------------------------------------------------

create table ${schema}.daily_login_bonus_xp_users (
    user_id bigint generated always as identity primary key,
    external_user_id text not null,
    reward_tz text not null,
    segment_key text null,
    created_at timestamptz not null default ${schema}.now_utc(),
    updated_at timestamptz not null default ${schema}.now_utc()
);

create unique index daily_login_bonus_xp_users_external_user_id_uidx on ${schema}.daily_login_bonus_xp_users (external_user_id);
create index daily_login_bonus_xp_users_reward_tz_idx on ${schema}.daily_login_bonus_xp_users (reward_tz);

comment on table ${schema}.daily_login_bonus_xp_users is 'Anchor record for every player eligible for XP tracking.';
comment on column ${schema}.daily_login_bonus_xp_users.user_id is 'Surrogate identifier generated by Postgres for each XP user.';
comment on column ${schema}.daily_login_bonus_xp_users.external_user_id is 'Platform-specific identifier for the player (e.g., account id).';
comment on column ${schema}.daily_login_bonus_xp_users.reward_tz is 'IANA timezone used to compute the player''s reward day boundary.';
comment on column ${schema}.daily_login_bonus_xp_users.segment_key is 'Optional live-ops segment or cohort label for personalization.';
comment on column ${schema}.daily_login_bonus_xp_users.created_at is 'Timestamp when the XP user row was created.';
comment on column ${schema}.daily_login_bonus_xp_users.updated_at is 'Timestamp when the XP user row was last updated.';

-------------------------------------------------------------------------------

create table ${schema}.daily_login_bonus_xp_ledger (
    ledger_id bigint generated always as identity primary key,
    user_id bigint not null,
    amount bigint not null,
    reason text not null,
    correlation_id uuid not null,
    policy_key text not null,
    policy_version bigint not null,
    season_id text null,
    metadata jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default ${schema}.now_utc(),
    constraint daily_login_bonus_xp_ledger_amount_chk check (amount <> 0),
    constraint daily_login_bonus_xp_ledger_user_fk foreign key (user_id) references ${schema}.daily_login_bonus_xp_users (user_id) on delete cascade
);

create unique index daily_login_bonus_xp_ledger_correlation_id_uidx on ${schema}.daily_login_bonus_xp_ledger (correlation_id);
create index daily_login_bonus_xp_ledger_user_created_at_idx on ${schema}.daily_login_bonus_xp_ledger (user_id, created_at desc);
create index daily_login_bonus_xp_ledger_policy_idx on ${schema}.daily_login_bonus_xp_ledger (policy_key, policy_version);

comment on table ${schema}.daily_login_bonus_xp_ledger is 'Append-only journal of XP transactions.';
comment on column ${schema}.daily_login_bonus_xp_ledger.amount is 'Positive values credit XP; negative values debit XP.';
comment on column ${schema}.daily_login_bonus_xp_ledger.correlation_id is 'Idempotency key used to prevent duplicate ledger inserts.';
comment on column ${schema}.daily_login_bonus_xp_ledger.user_id is 'Foreign key to ${schema}.daily_login_bonus_xp_users linking the ledger entry to a player.';
comment on column ${schema}.daily_login_bonus_xp_ledger.reason is 'Categorical reason for the XP change (e.g., DAILY_LOGIN).';
comment on column ${schema}.daily_login_bonus_xp_ledger.policy_key is 'Identifier for the rule or policy that produced the entry.';
comment on column ${schema}.daily_login_bonus_xp_ledger.policy_version is 'Version number of the policy applied during this grant.';
comment on column ${schema}.daily_login_bonus_xp_ledger.season_id is 'Optional season identifier associated with the entry.';
comment on column ${schema}.daily_login_bonus_xp_ledger.metadata is 'Opaque JSON payload capturing contextual details for analytics.';
comment on column ${schema}.daily_login_bonus_xp_ledger.created_at is 'UTC timestamp when the ledger entry was recorded.';

-------------------------------------------------------------------------------

create table ${schema}.daily_login_bonus_xp_balance (
    user_id bigint primary key,
    current_balance bigint not null default 0,
    lifetime_xp bigint not null default 0,
    seasonal_xp bigint not null default 0,
    season_id text null,
    updated_at timestamptz not null default ${schema}.now_utc(),
    constraint daily_login_bonus_xp_balance_totals_chk check (
        current_balance >= 0
        and lifetime_xp >= 0
        and seasonal_xp >= 0
    ),
    constraint daily_login_bonus_xp_balance_user_fk foreign key (user_id) references ${schema}.daily_login_bonus_xp_users (user_id) on delete cascade
);

comment on table ${schema}.daily_login_bonus_xp_balance is 'Materialized view of user XP totals maintained by triggers.';
comment on column ${schema}.daily_login_bonus_xp_balance.user_id is 'Foreign key to ${schema}.daily_login_bonus_xp_users; doubles as the primary key.';
comment on column ${schema}.daily_login_bonus_xp_balance.current_balance is 'Current net XP balance after all ledger entries.';
comment on column ${schema}.daily_login_bonus_xp_balance.lifetime_xp is 'Cumulative XP granted over the lifetime of the user.';
comment on column ${schema}.daily_login_bonus_xp_balance.seasonal_xp is 'XP earned within the current season window.';
comment on column ${schema}.daily_login_bonus_xp_balance.season_id is 'Identifier for the active season tied to the seasonal totals.';
comment on column ${schema}.daily_login_bonus_xp_balance.updated_at is 'Timestamp when the balance snapshot was last refreshed.';

-------------------------------------------------------------------------------

create table ${schema}.daily_login_bonus_xp_streaks (
    user_id bigint primary key,
    current_streak int not null default 0,
    longest_streak int not null default 0,
    grace_used int not null default 0,
    last_reward_day_id text null,
    model_state jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default ${schema}.now_utc(),
    constraint daily_login_bonus_xp_streaks_non_negative_chk check (
        current_streak >= 0
        and longest_streak >= 0
        and grace_used >= 0
    ),
    constraint daily_login_bonus_xp_streaks_user_fk foreign key (user_id) references ${schema}.daily_login_bonus_xp_users (user_id) on delete cascade
);

create index daily_login_bonus_xp_streaks_last_reward_day_idx on ${schema}.daily_login_bonus_xp_streaks (last_reward_day_id);

comment on table ${schema}.daily_login_bonus_xp_streaks is 'Tracks consecutive-day login streak status for each user.';
comment on column ${schema}.daily_login_bonus_xp_streaks.user_id is 'Foreign key to ${schema}.daily_login_bonus_xp_users; exactly one row per user.';
comment on column ${schema}.daily_login_bonus_xp_streaks.current_streak is 'Current consecutive-day login streak length.';
comment on column ${schema}.daily_login_bonus_xp_streaks.longest_streak is 'Historical maximum streak achieved by the user.';
comment on column ${schema}.daily_login_bonus_xp_streaks.grace_used is 'Count of grace days consumed under the active policy.';
comment on column ${schema}.daily_login_bonus_xp_streaks.last_reward_day_id is 'Last reward-day date (YYYY-MM-DD) in the user''s reward timezone that the streak engine processed.';
comment on column ${schema}.daily_login_bonus_xp_streaks.model_state is 'JSON blob storing policy-specific streak state.';
comment on column ${schema}.daily_login_bonus_xp_streaks.updated_at is 'Timestamp when the streak snapshot was last updated.';

-------------------------------------------------------------------------------

create table ${schema}.daily_login_bonus_xp_rules (
    policy_key text not null,
    version int not null,
    is_active boolean not null default false,
    definition jsonb not null,
    created_by text not null,
    created_at timestamptz not null default ${schema}.now_utc(),
    updated_at timestamptz not null default ${schema}.now_utc(),
    constraint daily_login_bonus_xp_rules_pk primary key (policy_key, version)
);

create unique index daily_login_bonus_xp_rules_active_uidx on ${schema}.daily_login_bonus_xp_rules (policy_key) where (is_active);

comment on table ${schema}.daily_login_bonus_xp_rules is 'Versioned policy documents that drive XP rules configuration.';
comment on column ${schema}.daily_login_bonus_xp_rules.policy_key is 'Stable identifier for the logical policy (e.g., daily_login).';
comment on column ${schema}.daily_login_bonus_xp_rules.version is 'Monotonic version number for the policy document.';
comment on column ${schema}.daily_login_bonus_xp_rules.is_active is 'Indicates whether this policy version is currently active.';
comment on column ${schema}.daily_login_bonus_xp_rules.definition is 'JSON payload describing base XP, curves, grace, and multipliers.';
comment on column ${schema}.daily_login_bonus_xp_rules.created_by is 'Operator or system that published this policy version.';
comment on column ${schema}.daily_login_bonus_xp_rules.created_at is 'Timestamp when the policy version was created.';
comment on column ${schema}.daily_login_bonus_xp_rules.updated_at is 'Timestamp when metadata for the policy version was last touched.';

-------------------------------------------------------------------------------

create table ${schema}.daily_login_bonus_xp_awards (
    award_id bigint generated always as identity primary key,
    user_id bigint not null,
    reward_day_id text not null,
    xp_awarded bigint not null,
    streak_day int not null,
    policy_key text not null,
    policy_version bigint not null,
    receipt_id uuid not null,
    model_state_snapshot jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default ${schema}.now_utc(),
    constraint daily_login_bonus_xp_awards_positive_chk check (xp_awarded > 0 and streak_day >= 0),
    constraint daily_login_bonus_xp_awards_user_fk foreign key (user_id) references ${schema}.daily_login_bonus_xp_users (user_id) on delete cascade
);

create unique index daily_login_bonus_xp_awards_user_day_uidx on ${schema}.daily_login_bonus_xp_awards (user_id, reward_day_id);
create index daily_login_bonus_xp_awards_policy_idx on ${schema}.daily_login_bonus_xp_awards (policy_key, policy_version);
create index daily_login_bonus_xp_awards_reward_day_idx on ${schema}.daily_login_bonus_xp_awards (reward_day_id);

comment on table ${schema}.daily_login_bonus_xp_awards is 'Idempotent record of daily login XP claims per user.';
comment on column ${schema}.daily_login_bonus_xp_awards.award_id is 'Surrogate key for the award row.';
comment on column ${schema}.daily_login_bonus_xp_awards.user_id is 'Foreign key to ${schema}.daily_login_bonus_xp_users for the claimant.';
comment on column ${schema}.daily_login_bonus_xp_awards.reward_day_id is 'Reward-day date (YYYY-MM-DD) evaluated in the player''s reward timezone at grant time.';
comment on column ${schema}.daily_login_bonus_xp_awards.xp_awarded is 'Amount of XP granted for the reward day.';
comment on column ${schema}.daily_login_bonus_xp_awards.streak_day is 'Derived streak index associated with the award.';
comment on column ${schema}.daily_login_bonus_xp_awards.policy_key is 'Policy key responsible for the award.';
comment on column ${schema}.daily_login_bonus_xp_awards.policy_version is 'Policy version used when computing the award.';
comment on column ${schema}.daily_login_bonus_xp_awards.receipt_id is 'Stable receipt returned to clients for duplicate detection.';
comment on column ${schema}.daily_login_bonus_xp_awards.model_state_snapshot is 'Copy of streak/policy state at the moment of claim.';
comment on column ${schema}.daily_login_bonus_xp_awards.created_at is 'Timestamp when the award was recorded.';
