using System;
using PlayerEngagement.Infrastructure.Persistence.DTOs.DailyLoginBonus.XPGrant;

namespace PlayerEngagement.Infrastructure.Tests.TestUtilities.DailyLoginBonus.XPGrant;

internal static class PolicyDtoFactory {
    internal static ActivePolicyDTO CreateActive(
        string policyKey,
        long policyId = 10,
        long version = 1,
        string? displayName = null,
        string description = "desc",
        string status = "Published",
        int baseXpAmount = 100,
        string currency = "XP",
        int claimWindowStartMinutes = 30,
        int claimWindowDurationHours = 4,
        string anchorStrategy = "ANCHOR_TIMEZONE",
        int graceAllowedMisses = 1,
        int graceWindowDays = 2,
        string modelType = "DECAY_CURVE",
        string modelParameters = "{\"decayPercent\":0.2,\"graceDay\":1}",
        int previewSampleWindowDays = 5,
        string previewDefaultSegment = "default",
        string seasonalMetadata = "{}",
        DateTime? effectiveAt = null,
        DateTime? supersededAt = null,
        DateTime? createdAt = null,
        string createdBy = "agent",
        DateTime? publishedAt = null) =>
        new(
            policyId,
            policyKey,
            displayName ?? $"{policyKey}-display",
            description,
            version,
            status,
            baseXpAmount,
            currency,
            claimWindowStartMinutes,
            claimWindowDurationHours,
            anchorStrategy,
            graceAllowedMisses,
            graceWindowDays,
            modelType,
            modelParameters,
            previewSampleWindowDays,
            previewDefaultSegment,
            seasonalMetadata,
            effectiveAt ?? DateTime.UtcNow.AddHours(-1),
            supersededAt,
            createdAt ?? DateTime.UtcNow.AddDays(-2),
            createdBy,
            publishedAt ?? DateTime.UtcNow.AddDays(-1));

    internal static PolicyVersionDTO CreateVersion(
        string policyKey,
        long policyId = 10,
        long version = 1,
        string? displayName = null,
        string description = "desc",
        string status = "Published",
        int baseXpAmount = 100,
        string currency = "XP",
        int claimWindowStartMinutes = 30,
        int claimWindowDurationHours = 4,
        string anchorStrategy = "ANCHOR_TIMEZONE",
        int graceAllowedMisses = 1,
        int graceWindowDays = 2,
        string modelType = "MILESTONE_META_REWARD",
        string modelParameters = "{\"milestones\":[{\"day\":7,\"rewardType\":\"badge\",\"rewardValue\":\"bronze\"}]}",
        int previewSampleWindowDays = 5,
        string previewDefaultSegment = "default",
        string seasonalMetadata = "{}",
        DateTime? effectiveAt = null,
        DateTime? supersededAt = null,
        DateTime? createdAt = null,
        string createdBy = "agent",
        DateTime? publishedAt = null) =>
        new(
            policyId,
            policyKey,
            displayName ?? $"{policyKey}-display",
            description,
            version,
            status,
            baseXpAmount,
            currency,
            claimWindowStartMinutes,
            claimWindowDurationHours,
            anchorStrategy,
            graceAllowedMisses,
            graceWindowDays,
            modelType,
            modelParameters,
            previewSampleWindowDays,
            previewDefaultSegment,
            seasonalMetadata,
            effectiveAt,
            supersededAt,
            createdAt ?? DateTime.UtcNow.AddDays(-2),
            createdBy,
            publishedAt ?? DateTime.UtcNow.AddDays(-1));
}
